[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"
  # Forzar el uso de npm
  NETLIFY_USE_NPM = "true"