[build]
  command = "npm run build"
  publish = "out"
  
[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--legacy-peer-deps"

# No necesitamos el plugin Next.js ya que estamos usando output: 'export'
# [[plugins]]
#   package = "@netlify/plugin-nextjs"